apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: metaflow-pvc
  namespace: team-dc
spec:
  accessModes:
    - ReadWriteMany  # Important: multiple pods need to access it
  resources:
    requests:
      storage: 100Gi  # Adjust size as needed
  storageClassName: standard-rwx  # Use your cluster's storage class
